### ISSUE TITLE
积分大乱斗

### ISSUE THREAD

**Issue by kuake0** [Mashiro2000/HeyTap#13]
积分大乱斗有俩个版本的，一个是真我的一个是欢太的，建议作者增加自动完成欢太大乱斗的任务https://hd.oppo.com/act/m/2021/huantaishangchengjif/index.html

**Comment by kuake0** [comment]
欢太商城的积分大乱斗任务更多

**Comment by Mashiro2000** [comment]
好的

**Comment by Mashiro2000** [comment]
> 欢太商城的积分大乱斗任务更多

欢太积分大乱斗已完成，移步[HeyTapTask](https://github.com/Mashiro2000/HeyTapTask)
