### ISSUE TITLE
主任务报错

### ISSUE THREAD

**Issue by CODYI1** [Mashiro2000/HeyTap#2]
C:\Users\YI\Desktop\HeyTap>python HeyTap.py
任务:任务中心
时间:2021-09-16 20:16:05
...     登录成功
...      失败原因:auth token is empty
****************************************

ck 和 ua在其他脚本可正常运行。求解决

**Comment by Mashiro2000** [comment]
再抓一次，有时候我也这样，很奇怪，
我是先访问任务中心，再访问领劵中心

**Comment by Mashiro2000** [comment]
你试试看，不行的话，我找个时间，康康是缺少那个cookie，才导致运行失败

**Comment by Mashiro2000** [comment]
脚本的反馈也很清楚了
登录是没问题，但错误原因是:auth token is empty

**Comment by CODYI1** [comment]
应该不是cookies的问题，https://github.com/hwkxk/HeytapTask 这个老哥的脚本也有一个类似的获取任务列表的函数，我的cookies和ua在这个脚本里执行是没问题的。

**Comment by Mashiro2000** [comment]
测试cookie的连接，我这边是采用APP的，出现这种问题，这位老哥的建议是[重新登录](https://github.com/hwkxk/HeytapTask/issues/41#issuecomment-913500552)

**Comment by Mashiro2000** [comment]
我今天去测试下，尽量给个答案，

**Comment by CODYI1** [comment]
很奇怪，重复了几次终于成功。不懂是不是cookies的问题，之前不成功的都是token打头的，后面抓到一个source_type打头的cookies就OK了。
