### ISSUE TITLE
qinglong面板运行报错

### ISSUE THREAD

**Issue by 166679551** [Mashiro2000/HeyTap#3]
![V1X6P@DLH_QEYE_~P)5GI B](https://user-images.githubusercontent.com/82209036/133641403-748dd510-7b47-4cf6-9bdc-b416a1f9ace2.png)
Traceback (most recent call last):
  File "HeyTap.py", line 522, in <module>
    heyTap.start()
  File "HeyTap.py", line 512, in start
    self.runTaskCenter()                    # 运行任务中心
  File "HeyTap.py", line 472, in runTaskCenter
    self.runViewPush()          # 浏览推送任务
  File "HeyTap.py", line 229, in runViewPush
    if self.pushData['completeStatus'] == 0:
AttributeError: 'HeyTap' object has no attribute 'pushData'

**Comment by Mashiro2000** [comment]
抱歉，我是一键替换，换值换错了，等等改

**Comment by 166679551** [comment]
> 抱歉，我是一键替换，换值换错了，等等改

好的谢谢回复

**Comment by Mashiro2000** [comment]
原因查明了，欢太商城的<点击推送>任务下架了，导致脚本错误运行，
注释掉472行即可
[742](https://github.com/Mashiro2000/HeyTap/blob/main/HeyTap.py#L472)

**Comment by Mashiro2000** [comment]
我这个脚本日志功能就是向着青龙开发的，主要是不了解青龙的运行原理，所以目前日志只能自己整路径(丢人)

**Comment by Mashiro2000** [comment]
[适配青龙面板](https://github.com/Mashiro2000/QL_HeyTap)
