### ISSUE TITLE
早起打卡

### ISSUE THREAD

**Issue by lishangyi** [Mashiro2000/HeyTap#5]
大佬，能做一个oppo社区的早起打卡吗？

**Comment by Mashiro2000** [comment]
oppo社区是其他软件吗

**Comment by lishangyi** [comment]
> oppo社区是其他软件吗

也是oppo的软件，里面有个早起打卡，跟早睡差不多的

**Comment by Mashiro2000** [comment]
> > oppo社区是其他软件吗
> 
> 也是oppo的软件，里面有个早起打卡，跟早睡差不多的

有空的时候，再去了解下
